apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-csi-cephfs-provisioner
  namespace: ns-rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-csi-cephfs-provisioner
  template:
    metadata:
      labels:
        app: rook-ceph-csi-cephfs-provisioner
    spec:
      serviceAccountName: rook-csi-cephfs-provisioner-sa
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: cephcsi
          image: quay.io/cephcsi/cephcsi:v3.9.0
          args:
            - "--type=cephfs"
            - "--drivername=cephfs.csi.ceph.com"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=5"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

      volumes:
        - name: socket-dir
          emptyDir: {}
