apiVersion: v1
kind: Service
metadata:
  name: backend-metrics
  namespace: ns-app
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      nodePort: 32001
