apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: ns-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: loki-data-pv
