apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-metrics
  namespace: argocd
  labels:
    app: argocd-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-metrics
  template:
    metadata:
      labels:
        app: argocd-metrics
    spec:
      containers:
        - name: metrics
          image: quay.io/argoproj/argocd:v2.14.6
          command: ["/usr/local/bin/argocd"]
          args: ["metrics"]
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-metrics
  namespace: argocd
  labels:
    app: argocd-metrics
spec:
  selector:
    app: argocd-metrics
  ports:
    - name: metrics
      port: 8082
      targetPort: 8082
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: ns-monitoring
  labels:
    release: prometheus-grafana
spec:
  selector:
    matchLabels:
      app: argocd-metrics
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
