apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-exporter
  namespace: argocd
  labels:
    app: argocd-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-exporter
  template:
    metadata:
      labels:
        app: argocd-exporter
    spec:
      containers:
        - name: exporter
          image: ghcr.io/akuity/argocd-exporter:v0.7.0
          args:
            - --argo-server-address=http://argocd-server.argocd.svc.cluster.local:80
            - --insecure
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-exporter
  namespace: argocd
  labels:
    app: argocd-exporter
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: argocd-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-exporter
  namespace: ns-monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: argocd-exporter
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
