apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller
  namespace: ns-monitoring
  labels:
    release: prometheus-grafana
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  namespaceSelector:
    matchNames:
      - ingress-nginx
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scheme: http
