apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: ns-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: exporter
          image: quay.io/prometheuscommunity/postgres-exporter
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://guardian:guardian@postgres.ns-db.svc:5432/guardian?sslmode=disable"
          ports:
            - containerPort: 9187
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9187
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9187
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: ns-db
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
