apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-exporter
  namespace: ns-vault
  labels:
    app: vault-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-exporter
  template:
    metadata:
      labels:
        app: vault-exporter
    spec:
      containers:
        - name: exporter
          image: giantswarm/vault-exporter:latest
          args:
            - --web.listen-address=:9410
            - --web.telemetry-path=/metrics
          env:
            - name: VAULT_ADDR
              value: http://vault.ns-vault.svc:8200
            - name: VAULT_SKIP_VERIFY
              value: "true"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-exporter-token
                  key: token
          ports:
            - name: http
              containerPort: 9410
---
apiVersion: v1
kind: Service
metadata:
  name: vault-exporter
  namespace: ns-vault
  labels:
    app: vault-exporter
spec:
  selector:
    app: vault-exporter
  ports:
    - name: http
      port: 9410
      targetPort: 9410
