apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-password
  namespace: ns-devops
type: Opaque
data:
  HARBOR_ADMIN_PASSWORD: aGFyYm9y #harbor
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-postgres-secret
  namespace: ns-devops
type: Opaque
data:
  POSTGRES_PASSWORD: aGFyYm9y #harbor