- job_name: 'cloud-node-exporter'
  static_configs:
    - targets:
        - 10.100.0.21:9100
        - 10.100.0.22:9100
        - 10.100.0.23:9100
  relabel_configs:
    - target_label: cluster
      replacement: cloud-cluster

- job_name: 'springboot-backend'
  metrics_path: /actuator/prometheus
  static_configs:
    - targets:
        - 10.100.0.21:32001
        - 10.100.0.22:32001
        - 10.100.0.23:32001
  relabel_configs:
    - target_label: cluster
      replacement: cloud-cluster

- job_name: 'nginx-ingress'
  metrics_path: /metrics
  static_configs:
    - targets:
        - 10.100.0.21:10254
        - 10.100.0.22:10254
        - 10.100.0.23:10254
  relabel_configs:
    - target_label: cluster
      replacement: cloud-cluster

- job_name: 'cloud-federation'
  scrape_interval: 30s
  metrics_path: /federate
  params:
    'match[]':
      - '{__name__=~".+"}'
  static_configs:
    - targets:
        - 10.100.0.21:30603
  relabel_configs:
    - target_label: cluster
      replacement: cloud-cluster
