apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-scrape-configs
  namespace: ns-monitoring
data:
  additional-scrape-configs.yaml: |
    - job_name: 'cloud-node-exporter'
      static_configs:
        - targets:
            - 10.100.0.21:9100
            - 10.100.0.22:9100
            - 10.100.0.23:9100
      relabel_configs:
        - source_labels: [__address__]
          target_label: cluster
          replacement: cloud

    - job_name: 'springboot-backend'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets:
            - 10.100.0.21:32001
            - 10.100.0.22:32001
            - 10.100.0.23:32001

    - job_name: 'cloud-kube-state-metrics'
      static_configs:
        - targets:
            - 10.100.0.21:31080
            - 10.100.0.22:31080
            - 10.100.0.23:31080
      relabel_configs:
        - source_labels: [__address__]
          target_label: cluster
          replacement: cloud

    - job_name: 'nginx-ingress'
      metrics_path: /metrics
      static_configs:
        - targets:
            - 10.100.0.21:10254
            - 10.100.0.22:10254
            - 10.100.0.23:10254
