apiVersion: v1
kind: Secret
metadata:
  name: cloud-scrape-configs
  namespace: ns-monitoring
type: Opaque
stringData:
  additional-scrape-configs.yaml: |
    - job_name: 'cloud-node-exporter'
      static_configs:
        - targets:
            - 10.100.0.21:9100
            - 10.100.0.22:9100
            - 10.100.0.23:9100
