apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BeeGuardians/Guardians-Infra.git
    targetRevision: feat/monitoring
    path: onpremise-cluster/monitoring/kube-prometheus-stack/charts/crds/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true
