apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BeeGuardians/Guardians-Infra.git
    targetRevision: dev-v2
    path: cloud-cluster/monitoring/kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
