apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BeeGuardians/Guardians-Infra.git
    targetRevision: feat/new-frontend
    path: cloud-cluster/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
