apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-hc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.14.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/BeeGuardians/Guardians-Infra/feat/harbor-hc/onpremise-cluster/harbor/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
