apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BeeGuardians/Guardians-Infra.git
    targetRevision: dev
    path: onpremise-cluster/harbor
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: harbor-jobservice
      namespace: harbor
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1configmap
        - /spec/template/metadata/annotations/checksum~1configmap-env
        - /spec/template/metadata/annotations/checksum~1secret
        - /spec/template/metadata/annotations/checksum~1secret-core
    - group: apps
      kind: Deployment
      name: harbor-registry
      namespace: harbor
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1configmap
        - /spec/template/metadata/annotations/checksum~1secret
