apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BeeGuardians/Guardians-Infra.git
    targetRevision: feat/jenkins
    path: onpremise-cluster/jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
