apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guardians-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BeeGuardians/Guardians-Infra.git
    targetRevision: dev-v2
    path: argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
