apiVersion: v1
kind: Service
metadata:
  name: frontend-dev
  namespace: ns-app
spec:
  selector:
    app: frontend-dev
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
