apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-inner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.14.0
    helm:
      parameters:
        - name: persistence.persistentVolumeClaim.registry.existingClaim
          value: harbor-inner-registry
        - name: persistence.persistentVolumeClaim.jobservice.existingClaim
          value: harbor-inner-jobservice
        - name: persistence.persistentVolumeClaim.database.existingClaim
          value: harbor-inner-database
        - name: persistence.persistentVolumeClaim.redis.existingClaim
          value: harbor-inner-redis
        - name: persistence.persistentVolumeClaim.trivy.existingClaim
          value: harbor-inner-trivy
        - name: persistence.imageChartStorage.filesystem.existingClaim
          value: harbor-inner-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true