# CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: harborclusters.goharbor.io
spec:
  group: goharbor.io
  names:
    kind: HarborCluster
    listKind: HarborClusterList
    plural: harborclusters
    singular: harborcluster
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
---
# Controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-operator
  namespace: ns-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-operator
  template:
    metadata:
      labels:
        app: harbor-operator
    spec:
      containers:
        - name: harbor-operator
          image: goharbor/harbor-operator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9443
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
