apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-inner-redis-0
  namespace: ns-devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 500Mi
  volumeName: pv-harbor-inner-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-inner-trivy-0
  namespace: ns-devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 500Mi
  volumeName: pv-harbor-inner-trivy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-inner-registry
  namespace: ns-devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-harbor-inner-registry