expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.guardians.local
      notary: notary.harbor.guardians.local
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"

externalURL: http://harbor.guardians.local

harborAdminPassword:
  existingSecret: harbor-admin-password

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      enabled: true
      existingClaim: harbor-registry
    jobservice:
      enabled: true
      existingClaim: harbor-jobservice
    database:
      enabled: true
      existingClaim: database-data-harbor-database-0
    redis:
      enabled: true
      existingClaim: data-harbor-redis-0
  resourcePolicy: "keep"

database:
  type: internal

trivy:
  enabled: true
  persistence:
    enabled: true
    existingClaim: data-harbor-trivy-0
    resourcePolicy: "keep"