expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    ingressClassName: nginx
    hosts:
      core: core.harbor.domain
    annotations:
      helm.sh/resource-policy: keep
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

externalURL: http://core.harbor.domain

harborAdminPassword:
  existingSecret: harbor-admin-password

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-registry
      enabled: true
    jobservice:
      existingClaim: harbor-jobservice
      enabled: true
    database:
      existingClaim: database-data-harbor-database-0
      enabled: false
    redis:
      existingClaim: data-harbor-redis-0
      enabled: false
  resourcePolicy: "keep"

database:
  type: internal

trivy:
  enabled: true
  persistence:
    enabled: true
    existingClaim: data-harbor-trivy-0
    resourcePolicy: "keep"