expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.guardians.com
    controller: default
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

externalURL: http://harbor.guardians.com

harborAdminPassword:
  existingSecret: harbor-admin-password

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-registry
      enabled: false
    jobservice:
      existingClaim: harbor-jobservice
      enabled: false
    database:
      existingClaim: database-data-harbor-database-0
      enabled: false
    redis:
      existingClaim: data-harbor-redis-0
      enabled: false
  resourcePolicy: "keep"

database:
  type: internal

trivy:
  enabled: true
  persistence:
    enabled: true
    existingClaim: data-harbor-trivy-0
    resourcePolicy: "keep"