expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.guardians.com

externalURL: http://harbor.guardians.com

existingSecret: harbor-admin-password

persistence:
  enabled: true
  resourcePolicy: "retain"

  persistentVolumeClaim:
    registry:
      existingClaim: ""
      storageClass: rook-ceph-block
    jobservice:
      existingClaim: ""
      storageClass: rook-ceph-block
    database:
      existingClaim: ""
      storageClass: rook-ceph-block
    redis:
      existingClaim: ""
      storageClass: rook-ceph-block
    trivy:
      existingClaim: ""
      storageClass: rook-ceph-block

  imageChartStorage:
    disableredirect: true
    filesystem:
      rootdirectory: /storage
      storageClass: rook-ceph-block