expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.guardians.com

externalURL: http://harbor.guardians.com

existingSecret: harbor-admin-password

persistence:
  enabled: true
  resourcePolicy: "retain"

  persistentVolumeClaim:
    registry:
      existingClaim: harbor-inner-registry
      storageClass: rook-ceph-block
    jobservice:
      existingClaim: harbor-inner-jobservice
      storageClass: rook-ceph-block
    database:
      existingClaim: database-data-harbor-inner-database-0
      storageClass: rook-ceph-block
    redis:
      existingClaim: data-harbor-inner-redis-0
      storageClass: rook-ceph-block
    trivy:
      existingClaim: data-harbor-inner-trivy-0
      storageClass: rook-ceph-block