expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.local
      notary: notary.harbor.local
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    tls:
      enabled: false

externalURL: http://harbor.local

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-registry
    jobservice:
      existingClaim: harbor-jobservice
    database:
<<<<<<< HEAD
      existingClaim: harbor-database
    redis:
      existingClaim: harbor-redis
    trivy:
      existingClaim: harbor-trivy
  imageChartStorage:
    disableredirect: true
=======
      existingClaim: database-data-harbor-database-0
    redis:
      existingClaim: data-harbor-redis-0
  resourcePolicy: "keep"
>>>>>>> parent of 3cea370 (fix : explicitly enable existing PVCs to avoid patch error)

database:
  internal:
    password: "Harbor12345"

harborAdminPassword: "Harbor12345"

trivy:
  enabled: true