# onpremise-cluster/monitoring/crds/kustomization.yaml
resources:
  - monitoring.coreos.com_alertmanagerconfigs.yaml
  - monitoring.coreos.com_podmonitors.yaml
  - monitoring.coreos.com_probes.yaml
  - monitoring.coreos.com_prometheusrules.yaml
  - monitoring.coreos.com_scrapeconfigs.yaml
  - monitoring.coreos.com_servicemonitors.yaml
  - monitoring.coreos.com_thanosrulers.yaml
