apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: ns-monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: argocd-metrics
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
