apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: ns-monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis
  namespaceSelector:
    matchNames:
      - ns-app
  endpoints:
    - port: metrics
      interval: 30s
