apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-servicemonitor
  namespace: ns-monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: redis-exporter
  namespaceSelector:
    matchNames:
      - ns-db
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
