apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault
  namespace: ns-monitoring
  labels:
    release: prometheus-grafana
spec:
  selector:
    matchLabels:
      app: vault
  namespaceSelector:
    matchNames:
      - ns-vault
  endpoints:
    - targetPort: 8200
      path: /v1/sys/metrics
      interval: 30s
