apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ns-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: default
      containers:
        - name: backend
          image: harbor.example.com:30443/guardians/backend:v10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres.ns-db.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "guardian"
            - name: REDIS_HOST
              value: "redis-service.ns-db.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: MAIL_HOST
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: role_id
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: secret_id
