apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ns-app
  labels:
    app: backend
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "backend"
    vault.hashicorp.com/agent-inject-secret-DB_USERNAME: "secret/data/guardians#DB_USERNAME"
    vault.hashicorp.com/agent-inject-secret-DB_PASSWORD: "secret/data/guardians#DB_PASSWORD"
    vault.hashicorp.com/agent-inject-secret-MAIL_USERNAME: "secret/data/guardians#MAIL_USERNAME"
    vault.hashicorp.com/agent-inject-secret-MAIL_PASSWORD: "secret/data/guardians#MAIL_PASSWORD"
    vault.hashicorp.com/agent-inject-secret-AWS_ACCESS_KEY: "secret/data/guardians#AWS_ACCESS_KEY"
    vault.hashicorp.com/agent-inject-secret-AWS_SECRET_KEY: "secret/data/guardians#AWS_SECRET_KEY"
    vault.hashicorp.com/agent-inject-secret-REDIS_PASSWORD: "secret/data/guardians#REDIS_PASSWORD"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: backend
          image: harbor.example.com:30443/guardians/backend:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres.ns-db.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "guardians"
            - name: REDIS_HOST
              value: "redis-service.ns-db.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: MAIL_HOST
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"

            # Vault-injected file paths as *_FILE
            - name: DB_USERNAME_FILE
              value: "/vault/secrets/DB_USERNAME"
            - name: DB_PASSWORD_FILE
              value: "/vault/secrets/DB_PASSWORD"
            - name: MAIL_USERNAME_FILE
              value: "/vault/secrets/MAIL_USERNAME"
            - name: MAIL_PASSWORD_FILE
              value: "/vault/secrets/MAIL_PASSWORD"
            - name: AWS_ACCESS_KEY_FILE
              value: "/vault/secrets/AWS_ACCESS_KEY"
            - name: AWS_SECRET_KEY_FILE
              value: "/vault/secrets/AWS_SECRET_KEY"
            - name: REDIS_PASSWORD_FILE
              value: "/vault/secrets/REDIS_PASSWORD"
