apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ns-app
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
