apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BeeGuardians/Guardians-Infra.git
    targetRevision: dev
    path: onpremise-cluster/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: postgres-secret
      namespace: ns-db
