apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: ns-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
