apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-refresh
  namespace: ns-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pgdata-refresh-pv
