apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-refresh-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins
