apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-v2
  namespace: ns-devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-fs
