apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: ns-devops
  labels:
    app.kubernetes.io/instance: jenkins
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZXhhbXBsZS5jb206MzA0NDMiOnsicGFzc3dvcmQiOiJLMUxkaEtDbmRQY2dlVVVqTjJrZ3djR0FKMmhrSEViZyIsInVzZXJuYW1lIjoicm9ib3QkZ3VhcmRpYW5zK2plbmtpbnMiLCJhdXRoIjoiY205aWIzUWtaM1ZhcmRwYVd5c0sybHB0aEJ0a1JuZFBjZ2VVVWpOMmtnd2NHQUsyaGtIRWJnIn19fQ==
