apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ns-devops
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30501
    - name: agent
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins
