apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-config
  namespace: rook-ceph
data:
  config: |
    [global]
    fsid = 066d868e-6f66-4db8-8722-c67c24950483
    mon_initial_members = mon-b,mon-c,mon-d
    mon_host = 10.110.204.242,10.102.6.167,10.104.35.254
    public network = 192.168.0.0/16
    cluster network = 192.168.0.0/16
