apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      containers:
        - name: rook-ceph-tools
          image: rook/ceph:v1.13.2
          command: ["/bin/bash"]
          args: ["-c", "sleep infinity"]
          tty: true
          stdin: true
          securityContext:
            privileged: true
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
      volumes:
        - name: ceph-conf
          configMap:
            name: rook-ceph-config
            items:
              - key: config
                path: ceph.conf
