apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      containers:
        - name: rook-ceph-tools
          image: rook/ceph:v1.13.2
          command: ["/bin/bash"]
          args: ["-c", "sleep infinity"]
          tty: true
          stdin: true
          securityContext:
            privileged: true
          env:
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-username
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-secret
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
            - name: ceph-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: ceph.client.admin.keyring
      volumes:
        - name: ceph-conf
          configMap:
            name: rook-ceph-config
            items:
              - key: config
                path: ceph.conf
        - name: ceph-keyring
          secret:
            secretName: rook-ceph-mon
            items:
              - key: ceph-secret
                path: ceph.client.admin.keyring
