apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      containers:
        - name: rook-ceph-tools
          image: rook/ceph:v1.13.2
          command: ["/tini"]
          args: ["-g", "--", "/usr/local/bin/toolbox.sh"]
          tty: true
          stdin: true
          securityContext:
            privileged: true
          env:
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: user
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: key
          volumeMounts:
            - name: ceph-config
              mountPath: /etc/ceph
      volumes:
        - name: ceph-config
          projected:
            sources:
              - configMap:
                  name: rook-ceph-config
              - secret:
                  name: rook-ceph-mon