apiVersion: v1
kind: Service
metadata:
  name: harbor-core
  namespace: ns-devops
  labels:
    app: harbor-core
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: harbor-core
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-core
  namespace: ns-devops
  labels:
    app: harbor-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-core
  template:
    metadata:
      labels:
        app: harbor-core
    spec:
      containers:
        - name: core
          image: goharbor/harbor-core:v2.10.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: harbor-core-config
          env:
            - name: HARBOR_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-admin-password
                  key: HARBOR_ADMIN_PASSWORD
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-postgres-secret
                  key: POSTGRES_PASSWORD