apiVersion: v1
kind: Service
metadata:
  name: harbor-jobservice
  namespace: ns-devops
  labels:
    app: harbor-jobservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: harbor-jobservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-jobservice
  namespace: ns-devops
  labels:
    app: harbor-jobservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-jobservice
  template:
    metadata:
      labels:
        app: harbor-jobservice
    spec:
      containers:
        - name: jobservice
          image: goharbor/harbor-jobservice:v2.10.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: harbor-core-config
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: jobservice-storage
              mountPath: /var/log/jobs
      volumes:
        - name: jobservice-storage
          persistentVolumeClaim:
            claimName: harbor-jobservice
