apiVersion: v1
kind: Service
metadata:
  name: harbor-nginx
  namespace: ns-devops
  labels:
    app: harbor-nginx
spec:
  type: NodePort
  selector:
    app: harbor-nginx
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30401
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-nginx
  namespace: ns-devops
  labels:
    app: harbor-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-nginx
  template:
    metadata:
      labels:
        app: harbor-nginx
    spec:
      containers:
        - name: nginx
          image: goharbor/nginx-photon:v2.10.0
          ports:
            - containerPort: 8080