apiVersion: v1
kind: Service
metadata:
  name: harbor-portal
  namespace: ns-devops
  labels:
    app: harbor-portal
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: harbor-portal
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-portal
  namespace: ns-devops
  labels:
    app: harbor-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-portal
  template:
    metadata:
      labels:
        app: harbor-portal
    spec:
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.10.0
          ports:
            - containerPort: 8080