apiVersion: v1
kind: Service
metadata:
  name: harbor-redis
  namespace: ns-devops
labels:
  app: harbor-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: harbor-redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-redis
  namespace: ns-devops
labels:
  app: harbor-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-redis
  template:
    metadata:
      labels:
        app: harbor-redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-storage
          args: ["--save", "60", "1", "--loglevel", "warning"]
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: harbor-redis