apiVersion: v1
kind: Service
metadata:
  name: harbor-registry
  namespace: ns-devops
  labels:
    app: harbor-registry
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: harbor-registry
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-registry
  namespace: ns-devops
  labels:
    app: harbor-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-registry
  template:
    metadata:
      labels:
        app: harbor-registry
    spec:
      containers:
        - name: registry
          image: goharbor/registry-photon:v2.10.0
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /storage
          volumeMounts:
            - name: registry-storage
              mountPath: /storage
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: harbor-registry
