apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      containers:
        - name: rook-ceph-tools
          image: quay.io/ceph/ceph:v18.2.1
          command: ["/bin/bash", "-c"]
          args:
            - |
              ceph config set mgr mgr/cephadm/log_to_journald false || true
              ceph config set global log_to_stderr false || true
              ceph config set global mon_cluster_log_to_stderr false || true
              tail -f /dev/null
          env:
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-username
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-secret
          volumeMounts:
            - name: mon-endpoint-volume
              mountPath: /etc/rook
            - name: ceph-admin-secret
              mountPath: /var/lib/rook-ceph-mon
              readOnly: true
            - name: ceph-config
              mountPath: /etc/ceph
      volumes:
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
        - name: ceph-admin-secret
          secret:
            secretName: rook-ceph-mon
        - name: ceph-config
          emptyDir: {}
      serviceAccountName: rook-ceph-system
