apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-monitoring

resources:
  # Grafana Dashboards
  - grafana-dashboard/vault-dashboard.yaml
  - grafana-dashboard/ceph-dashboard.yaml
  - grafana-dashboard/harbor-dashboard.yaml
  - grafana-dashboard/jenkins-dashboard.yaml
  - grafana-dashboard/argocd-dashboard.yaml
  - grafana-dashboard/node-dashboard.yaml
  - grafana-dashboard/postgres-dashboard.yaml

  # ServiceMonitors
  - servicemonitor/vault.yaml
  - servicemonitor/ceph.yaml
  - servicemonitor/harbor.yaml
  - servicemonitor/jenkins.yaml
  - servicemonitor/argocd.yaml