apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: false
    nodes:
      - name: "guardians2"
        devices:
          - name: "sdb"
      - name: "guardians3"
        devices:
          - name: "sdb"
      - name: "guardians4"
        devices:
          - name: "sdb"
    config:
      osdsPerDevice: "1"
