apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - name: myfs-data0
      replicated:
        size: 3
  metadataServer:
    activeCount: 1
    activeStandby: true
