apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-operator
  template:
    metadata:
      labels:
        app: rook-ceph-operator
    spec:
      containers:
        - name: rook-ceph-operator
          image: rook/ceph:v1.13.3
          args: ["ceph"]
          env:
            - name: ROOK_ENABLE_SELINUX_RELABELING
              value: "true"
            - name: ROOK_LOG_LEVEL
              value: "DEBUG"
          securityContext:
            privileged: true
      serviceAccountName: rook-ceph-system
