apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: ns-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
        - name: vault
          image: hashicorp/vault:1.14.5
          args:
            - "server"
          ports:
            - containerPort: 8200
            - containerPort: 9102
          volumeMounts:
            - mountPath: /vault/data
              name: vault-storage
          env:
            - name: VAULT_LOCAL_CONFIG
              value: |
                {
                  "backend": {
                    "file": {
                      "path": "/vault/data"
                    }
                  },
                  "listener": {
                    "tcp": {
                      "address": "0.0.0.0:8200",
                      "tls_disable": true
                    }
                  },
                  "ui": true,
                  "api_addr": "http://0.0.0.0:8200",
                  "telemetry": {
                    "prometheus_retention_time": "30s",
                    "disable_hostname": true,
                    "listen_address": "0.0.0.0:9102"
                  }
                }
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      volumes:
        - name: vault-storage
          persistentVolumeClaim:
            claimName: vault-data
