apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/vault
