apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: ns-vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      nodePort: 30301
    - name: telemetry
      port: 9102
      targetPort: 9102
 